@setupMapWithLocations = (locations, markerURL) ->
  $(document).ready ->
    initialize locations, markerURL
    return
  return

initialize = (locations, markerURL) ->
  myLatlng = new (google.maps.LatLng)(locations[0].latitude, locations[0].longitude)
  mapOptions = 
    center: myLatlng
    zoom: 8
    panControl: false
    zoomControl: true
    zoomControlOptions:
      style: google.maps.ZoomControlStyle.SMALL
      position: google.maps.ControlPosition.RIGHT_TOP
    mapTypeControl: false
    scaleControl: false
    streetViewControl: false
    overviewMapControl: false
  map = new (google.maps.Map)(document.getElementById('map-canvas'), mapOptions)
  locations.forEach (location) ->
    thisLatLng = new (google.maps.LatLng)(location.latitude, location.longitude)
    marker = new (google.maps.Marker)(
      position: thisLatLng
      map: map
      title: location.name
      icon: markerURL)
    infowindow = new (google.maps.InfoWindow)(content: location.name)
    google.maps.event.addListener marker, 'click', ->
      infowindow.open map, marker
      return
    return
  # Create the DIV to hold the control and call the HomeControl() constructor
  # passing in this DIV.
  locationCountControlDiv = document.createElement('div')
  locationControl = new metricControl(locationCountControlDiv, map, 'Total # of location Yadas pinned', locations.length)
  locationControl.index = 1

  timeCountControlDiv = document.createElement('div')
  timeControl = new metricControl(timeCountControlDiv, map, 'Total # of time Yadas pinned', timeYadaCount)
  timeControl.index = 2

  totalCountControlDiv = document.createElement('div')
  totalControl = new metricControl(totalCountControlDiv, map, 'Total # of Yadas pinned', totalYadaCount)
  totalControl.index = 3

  map.controls[google.maps.ControlPosition.LEFT_TOP].push locationCountControlDiv
  map.controls[google.maps.ControlPosition.LEFT_TOP].push timeCountControlDiv
  map.controls[google.maps.ControlPosition.LEFT_TOP].push totalCountControlDiv
  return

metricControl = (controlDiv, map, label, metric) ->
  # Set CSS styles for the DIV containing the control
  # Setting padding to 5 px will offset the control
  # from the edge of the map.
  controlDiv.style.padding = '5px'
  # Set CSS for the control border.
  controlUI = document.createElement('div')
  controlUI.style.backgroundColor = 'white'
  controlUI.style.borderStyle = 'solid'
  controlUI.style.borderWidth = '2px'
  #controlUI.style.cursor = 'pointer';
  controlUI.style.textAlign = 'center'
  #controlUI.title = 'Click to set the map to Home';
  controlDiv.appendChild controlUI
  # Set CSS for the control interior.
  controlText = document.createElement('div')
  controlText.style.fontFamily = 'Arial,sans-serif'
  controlText.style.fontSize = '12px'
  controlText.style.paddingLeft = '4px'
  controlText.style.paddingRight = '4px'
  controlText.innerHTML = '<strong>' + label + ': <b>' + metric + '</b></strong>'
  controlUI.appendChild controlText
  # Setup the click event listeners: simply set the map to Chicago.
  google.maps.event.addDomListener controlUI, 'click', ->
    map.setCenter chicago
    return
  return


# ---
# generated by js2coffee 2.0.0